logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-contactsettings
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: contactsettings-pool
  flyway:
    enabled: false
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
